#!/bin/bash
mkdir -pv AD && wget http://files.docking.org/2D/AD/ADAA.smi -O AD/ADAA.smi
mkdir -pv AD && wget http://files.docking.org/2D/AD/ADAB.smi -O AD/ADAB.smi
mkdir -pv AD && wget http://files.docking.org/2D/AD/ADAC.smi -O AD/ADAC.smi
mkdir -pv AD && wget http://files.docking.org/2D/AD/ADAD.smi -O AD/ADAD.smi
mkdir -pv AD && wget http://files.docking.org/2D/AD/ADBA.smi -O AD/ADBA.smi
mkdir -pv AD && wget http://files.docking.org/2D/AD/ADBB.smi -O AD/ADBB.smi
mkdir -pv AD && wget http://files.docking.org/2D/AD/ADBC.smi -O AD/ADBC.smi
mkdir -pv AD && wget http://files.docking.org/2D/AD/ADBD.smi -O AD/ADBD.smi
mkdir -pv AD && wget http://files.docking.org/2D/AD/ADCA.smi -O AD/ADCA.smi
mkdir -pv AD && wget http://files.docking.org/2D/AD/ADCB.smi -O AD/ADCB.smi
mkdir -pv AD && wget http://files.docking.org/2D/AD/ADCC.smi -O AD/ADCC.smi
mkdir -pv AD && wget http://files.docking.org/2D/AD/ADCD.smi -O AD/ADCD.smi
mkdir -pv AD && wget http://files.docking.org/2D/AD/ADEA.smi -O AD/ADEA.smi
mkdir -pv AD && wget http://files.docking.org/2D/AD/ADEB.smi -O AD/ADEB.smi
mkdir -pv AD && wget http://files.docking.org/2D/AD/ADEC.smi -O AD/ADEC.smi
mkdir -pv AD && wget http://files.docking.org/2D/AD/ADED.smi -O AD/ADED.smi
mkdir -pv BD && wget http://files.docking.org/2D/BD/BDAA.smi -O BD/BDAA.smi
mkdir -pv BD && wget http://files.docking.org/2D/BD/BDAB.smi -O BD/BDAB.smi
mkdir -pv BD && wget http://files.docking.org/2D/BD/BDAC.smi -O BD/BDAC.smi
mkdir -pv BD && wget http://files.docking.org/2D/BD/BDAD.smi -O BD/BDAD.smi
mkdir -pv BD && wget http://files.docking.org/2D/BD/BDBA.smi -O BD/BDBA.smi
mkdir -pv BD && wget http://files.docking.org/2D/BD/BDBB.smi -O BD/BDBB.smi
mkdir -pv BD && wget http://files.docking.org/2D/BD/BDBC.smi -O BD/BDBC.smi
mkdir -pv BD && wget http://files.docking.org/2D/BD/BDBD.smi -O BD/BDBD.smi
mkdir -pv BD && wget http://files.docking.org/2D/BD/BDCA.smi -O BD/BDCA.smi
mkdir -pv BD && wget http://files.docking.org/2D/BD/BDCB.smi -O BD/BDCB.smi
mkdir -pv BD && wget http://files.docking.org/2D/BD/BDCC.smi -O BD/BDCC.smi
mkdir -pv BD && wget http://files.docking.org/2D/BD/BDCD.smi -O BD/BDCD.smi
mkdir -pv BD && wget http://files.docking.org/2D/BD/BDEA.smi -O BD/BDEA.smi
mkdir -pv BD && wget http://files.docking.org/2D/BD/BDEB.smi -O BD/BDEB.smi
mkdir -pv BD && wget http://files.docking.org/2D/BD/BDEC.smi -O BD/BDEC.smi
mkdir -pv BD && wget http://files.docking.org/2D/BD/BDED.smi -O BD/BDED.smi
mkdir -pv CD && wget http://files.docking.org/2D/CD/CDAA.smi -O CD/CDAA.smi
mkdir -pv CD && wget http://files.docking.org/2D/CD/CDAB.smi -O CD/CDAB.smi
mkdir -pv CD && wget http://files.docking.org/2D/CD/CDAC.smi -O CD/CDAC.smi
mkdir -pv CD && wget http://files.docking.org/2D/CD/CDAD.smi -O CD/CDAD.smi
mkdir -pv CD && wget http://files.docking.org/2D/CD/CDBA.smi -O CD/CDBA.smi
mkdir -pv CD && wget http://files.docking.org/2D/CD/CDBB.smi -O CD/CDBB.smi
mkdir -pv CD && wget http://files.docking.org/2D/CD/CDBC.smi -O CD/CDBC.smi
mkdir -pv CD && wget http://files.docking.org/2D/CD/CDBD.smi -O CD/CDBD.smi
mkdir -pv CD && wget http://files.docking.org/2D/CD/CDCA.smi -O CD/CDCA.smi
mkdir -pv CD && wget http://files.docking.org/2D/CD/CDCB.smi -O CD/CDCB.smi
mkdir -pv CD && wget http://files.docking.org/2D/CD/CDCC.smi -O CD/CDCC.smi
mkdir -pv CD && wget http://files.docking.org/2D/CD/CDCD.smi -O CD/CDCD.smi
mkdir -pv CD && wget http://files.docking.org/2D/CD/CDEA.smi -O CD/CDEA.smi
mkdir -pv CD && wget http://files.docking.org/2D/CD/CDEB.smi -O CD/CDEB.smi
mkdir -pv CD && wget http://files.docking.org/2D/CD/CDEC.smi -O CD/CDEC.smi
mkdir -pv CD && wget http://files.docking.org/2D/CD/CDED.smi -O CD/CDED.smi
mkdir -pv DD && wget http://files.docking.org/2D/DD/DDAA.smi -O DD/DDAA.smi
mkdir -pv DD && wget http://files.docking.org/2D/DD/DDAB.smi -O DD/DDAB.smi
mkdir -pv DD && wget http://files.docking.org/2D/DD/DDAC.smi -O DD/DDAC.smi
mkdir -pv DD && wget http://files.docking.org/2D/DD/DDAD.smi -O DD/DDAD.smi
mkdir -pv DD && wget http://files.docking.org/2D/DD/DDBA.smi -O DD/DDBA.smi
mkdir -pv DD && wget http://files.docking.org/2D/DD/DDBB.smi -O DD/DDBB.smi
mkdir -pv DD && wget http://files.docking.org/2D/DD/DDBD.smi -O DD/DDBD.smi
mkdir -pv DD && wget http://files.docking.org/2D/DD/DDCA.smi -O DD/DDCA.smi
mkdir -pv DD && wget http://files.docking.org/2D/DD/DDCB.smi -O DD/DDCB.smi
mkdir -pv DD && wget http://files.docking.org/2D/DD/DDCD.smi -O DD/DDCD.smi
mkdir -pv DD && wget http://files.docking.org/2D/DD/DDEA.smi -O DD/DDEA.smi
mkdir -pv DD && wget http://files.docking.org/2D/DD/DDEB.smi -O DD/DDEB.smi
mkdir -pv DD && wget http://files.docking.org/2D/DD/DDEC.smi -O DD/DDEC.smi
mkdir -pv DD && wget http://files.docking.org/2D/DD/DDED.smi -O DD/DDED.smi
mkdir -pv ED && wget http://files.docking.org/2D/ED/EDAA.smi -O ED/EDAA.smi
mkdir -pv ED && wget http://files.docking.org/2D/ED/EDAB.smi -O ED/EDAB.smi
mkdir -pv ED && wget http://files.docking.org/2D/ED/EDAC.smi -O ED/EDAC.smi
mkdir -pv ED && wget http://files.docking.org/2D/ED/EDAD.smi -O ED/EDAD.smi
mkdir -pv ED && wget http://files.docking.org/2D/ED/EDBA.smi -O ED/EDBA.smi
mkdir -pv ED && wget http://files.docking.org/2D/ED/EDBB.smi -O ED/EDBB.smi
mkdir -pv ED && wget http://files.docking.org/2D/ED/EDBD.smi -O ED/EDBD.smi
mkdir -pv ED && wget http://files.docking.org/2D/ED/EDCA.smi -O ED/EDCA.smi
mkdir -pv ED && wget http://files.docking.org/2D/ED/EDCB.smi -O ED/EDCB.smi
mkdir -pv ED && wget http://files.docking.org/2D/ED/EDCD.smi -O ED/EDCD.smi
mkdir -pv ED && wget http://files.docking.org/2D/ED/EDEA.smi -O ED/EDEA.smi
mkdir -pv ED && wget http://files.docking.org/2D/ED/EDEB.smi -O ED/EDEB.smi
mkdir -pv ED && wget http://files.docking.org/2D/ED/EDEC.smi -O ED/EDEC.smi
mkdir -pv ED && wget http://files.docking.org/2D/ED/EDED.smi -O ED/EDED.smi
mkdir -pv FD && wget http://files.docking.org/2D/FD/FDAA.smi -O FD/FDAA.smi
mkdir -pv FD && wget http://files.docking.org/2D/FD/FDAB.smi -O FD/FDAB.smi
mkdir -pv FD && wget http://files.docking.org/2D/FD/FDAC.smi -O FD/FDAC.smi
mkdir -pv FD && wget http://files.docking.org/2D/FD/FDAD.smi -O FD/FDAD.smi
mkdir -pv FD && wget http://files.docking.org/2D/FD/FDBA.smi -O FD/FDBA.smi
mkdir -pv FD && wget http://files.docking.org/2D/FD/FDBB.smi -O FD/FDBB.smi
mkdir -pv FD && wget http://files.docking.org/2D/FD/FDBC.smi -O FD/FDBC.smi
mkdir -pv FD && wget http://files.docking.org/2D/FD/FDBD.smi -O FD/FDBD.smi
mkdir -pv FD && wget http://files.docking.org/2D/FD/FDCA.smi -O FD/FDCA.smi
mkdir -pv FD && wget http://files.docking.org/2D/FD/FDCB.smi -O FD/FDCB.smi
mkdir -pv FD && wget http://files.docking.org/2D/FD/FDCD.smi -O FD/FDCD.smi
mkdir -pv FD && wget http://files.docking.org/2D/FD/FDEA.smi -O FD/FDEA.smi
mkdir -pv FD && wget http://files.docking.org/2D/FD/FDEB.smi -O FD/FDEB.smi
mkdir -pv FD && wget http://files.docking.org/2D/FD/FDEC.smi -O FD/FDEC.smi
mkdir -pv FD && wget http://files.docking.org/2D/FD/FDED.smi -O FD/FDED.smi
mkdir -pv GD && wget http://files.docking.org/2D/GD/GDAA.smi -O GD/GDAA.smi
mkdir -pv GD && wget http://files.docking.org/2D/GD/GDAB.smi -O GD/GDAB.smi
mkdir -pv GD && wget http://files.docking.org/2D/GD/GDAC.smi -O GD/GDAC.smi
mkdir -pv GD && wget http://files.docking.org/2D/GD/GDAD.smi -O GD/GDAD.smi
mkdir -pv GD && wget http://files.docking.org/2D/GD/GDBA.smi -O GD/GDBA.smi
mkdir -pv GD && wget http://files.docking.org/2D/GD/GDBB.smi -O GD/GDBB.smi
mkdir -pv GD && wget http://files.docking.org/2D/GD/GDBD.smi -O GD/GDBD.smi
mkdir -pv GD && wget http://files.docking.org/2D/GD/GDCA.smi -O GD/GDCA.smi
mkdir -pv GD && wget http://files.docking.org/2D/GD/GDCB.smi -O GD/GDCB.smi
mkdir -pv GD && wget http://files.docking.org/2D/GD/GDCD.smi -O GD/GDCD.smi
mkdir -pv GD && wget http://files.docking.org/2D/GD/GDEA.smi -O GD/GDEA.smi
mkdir -pv GD && wget http://files.docking.org/2D/GD/GDEB.smi -O GD/GDEB.smi
mkdir -pv GD && wget http://files.docking.org/2D/GD/GDED.smi -O GD/GDED.smi
mkdir -pv HD && wget http://files.docking.org/2D/HD/HDAA.smi -O HD/HDAA.smi
mkdir -pv HD && wget http://files.docking.org/2D/HD/HDAB.smi -O HD/HDAB.smi
mkdir -pv HD && wget http://files.docking.org/2D/HD/HDAC.smi -O HD/HDAC.smi
mkdir -pv HD && wget http://files.docking.org/2D/HD/HDAD.smi -O HD/HDAD.smi
mkdir -pv HD && wget http://files.docking.org/2D/HD/HDBA.smi -O HD/HDBA.smi
mkdir -pv HD && wget http://files.docking.org/2D/HD/HDBB.smi -O HD/HDBB.smi
mkdir -pv HD && wget http://files.docking.org/2D/HD/HDBC.smi -O HD/HDBC.smi
mkdir -pv HD && wget http://files.docking.org/2D/HD/HDBD.smi -O HD/HDBD.smi
mkdir -pv HD && wget http://files.docking.org/2D/HD/HDCA.smi -O HD/HDCA.smi
mkdir -pv HD && wget http://files.docking.org/2D/HD/HDCB.smi -O HD/HDCB.smi
mkdir -pv HD && wget http://files.docking.org/2D/HD/HDCD.smi -O HD/HDCD.smi
mkdir -pv HD && wget http://files.docking.org/2D/HD/HDEA.smi -O HD/HDEA.smi
mkdir -pv HD && wget http://files.docking.org/2D/HD/HDEB.smi -O HD/HDEB.smi
mkdir -pv HD && wget http://files.docking.org/2D/HD/HDEC.smi -O HD/HDEC.smi
mkdir -pv HD && wget http://files.docking.org/2D/HD/HDED.smi -O HD/HDED.smi
mkdir -pv ID && wget http://files.docking.org/2D/ID/IDAA.smi -O ID/IDAA.smi
mkdir -pv ID && wget http://files.docking.org/2D/ID/IDAB.smi -O ID/IDAB.smi
mkdir -pv ID && wget http://files.docking.org/2D/ID/IDAC.smi -O ID/IDAC.smi
mkdir -pv ID && wget http://files.docking.org/2D/ID/IDAD.smi -O ID/IDAD.smi
mkdir -pv ID && wget http://files.docking.org/2D/ID/IDBA.smi -O ID/IDBA.smi
mkdir -pv ID && wget http://files.docking.org/2D/ID/IDBB.smi -O ID/IDBB.smi
mkdir -pv ID && wget http://files.docking.org/2D/ID/IDBD.smi -O ID/IDBD.smi
mkdir -pv ID && wget http://files.docking.org/2D/ID/IDCA.smi -O ID/IDCA.smi
mkdir -pv ID && wget http://files.docking.org/2D/ID/IDCB.smi -O ID/IDCB.smi
mkdir -pv ID && wget http://files.docking.org/2D/ID/IDCC.smi -O ID/IDCC.smi
mkdir -pv ID && wget http://files.docking.org/2D/ID/IDCD.smi -O ID/IDCD.smi
mkdir -pv ID && wget http://files.docking.org/2D/ID/IDEA.smi -O ID/IDEA.smi
mkdir -pv ID && wget http://files.docking.org/2D/ID/IDEB.smi -O ID/IDEB.smi
mkdir -pv ID && wget http://files.docking.org/2D/ID/IDED.smi -O ID/IDED.smi
mkdir -pv JD && wget http://files.docking.org/2D/JD/JDAA.smi -O JD/JDAA.smi
mkdir -pv JD && wget http://files.docking.org/2D/JD/JDAB.smi -O JD/JDAB.smi
mkdir -pv JD && wget http://files.docking.org/2D/JD/JDAC.smi -O JD/JDAC.smi
mkdir -pv JD && wget http://files.docking.org/2D/JD/JDAD.smi -O JD/JDAD.smi
mkdir -pv JD && wget http://files.docking.org/2D/JD/JDBA.smi -O JD/JDBA.smi
mkdir -pv JD && wget http://files.docking.org/2D/JD/JDBB.smi -O JD/JDBB.smi
mkdir -pv JD && wget http://files.docking.org/2D/JD/JDBC.smi -O JD/JDBC.smi
mkdir -pv JD && wget http://files.docking.org/2D/JD/JDBD.smi -O JD/JDBD.smi
mkdir -pv JD && wget http://files.docking.org/2D/JD/JDCA.smi -O JD/JDCA.smi
mkdir -pv JD && wget http://files.docking.org/2D/JD/JDCB.smi -O JD/JDCB.smi
mkdir -pv JD && wget http://files.docking.org/2D/JD/JDCC.smi -O JD/JDCC.smi
mkdir -pv JD && wget http://files.docking.org/2D/JD/JDCD.smi -O JD/JDCD.smi
mkdir -pv JD && wget http://files.docking.org/2D/JD/JDEA.smi -O JD/JDEA.smi
mkdir -pv JD && wget http://files.docking.org/2D/JD/JDEB.smi -O JD/JDEB.smi
mkdir -pv JD && wget http://files.docking.org/2D/JD/JDEC.smi -O JD/JDEC.smi
mkdir -pv JD && wget http://files.docking.org/2D/JD/JDED.smi -O JD/JDED.smi
mkdir -pv KD && wget http://files.docking.org/2D/KD/KDAA.smi -O KD/KDAA.smi
mkdir -pv KD && wget http://files.docking.org/2D/KD/KDAB.smi -O KD/KDAB.smi
mkdir -pv KD && wget http://files.docking.org/2D/KD/KDAC.smi -O KD/KDAC.smi
mkdir -pv KD && wget http://files.docking.org/2D/KD/KDAD.smi -O KD/KDAD.smi
mkdir -pv KD && wget http://files.docking.org/2D/KD/KDBA.smi -O KD/KDBA.smi
mkdir -pv KD && wget http://files.docking.org/2D/KD/KDBB.smi -O KD/KDBB.smi
mkdir -pv KD && wget http://files.docking.org/2D/KD/KDBC.smi -O KD/KDBC.smi
mkdir -pv KD && wget http://files.docking.org/2D/KD/KDBD.smi -O KD/KDBD.smi
mkdir -pv KD && wget http://files.docking.org/2D/KD/KDCA.smi -O KD/KDCA.smi
mkdir -pv KD && wget http://files.docking.org/2D/KD/KDCB.smi -O KD/KDCB.smi
mkdir -pv KD && wget http://files.docking.org/2D/KD/KDCC.smi -O KD/KDCC.smi
mkdir -pv KD && wget http://files.docking.org/2D/KD/KDCD.smi -O KD/KDCD.smi
mkdir -pv KD && wget http://files.docking.org/2D/KD/KDEA.smi -O KD/KDEA.smi
mkdir -pv KD && wget http://files.docking.org/2D/KD/KDEB.smi -O KD/KDEB.smi
mkdir -pv KD && wget http://files.docking.org/2D/KD/KDEC.smi -O KD/KDEC.smi
mkdir -pv KD && wget http://files.docking.org/2D/KD/KDED.smi -O KD/KDED.smi

